### PR TITLE
Updating Versions & reformatting code

### LINKED ISSUE #1: Update solution to use .NET 8 (Latest)
The solution currently targets .NET 6. The latest .NET has been released this past November (.NET 8). This issue is to address the necessity to upgrade to the latest version to benefit from all performance and development improvements

## Tasks

- [x] Update all project TFM to `net8.0`
- [x] Update all `Microsoft.*` and `Microsoft.Extensions.*` to version `8.0.0`
- [x] Make sure all Libraries are compatible with .NET 8

## Hints

- Understand what .NET Standard is

### PR DESCRIPTION
**Pull request by saraabdelsalam**

### CODE REVIEW

**Review by YoussefWaelMohamedLotfy — CHANGES_REQUESTED** [review]
@saraabdelsalam The changes are fine, but I would like that you remove any deprecated packages in all projects. Here's a nice hint to help:

From within Visual Studio, Go to `Tools -> Nuget Package Manager -> Manage nuget packages for Solution...`, this will show all packages used in the solution. From there you can view the `Updates` tab and update all with a single click, or select only that you want to update.

image

**Comment by YoussefWaelMohamedLotfy** [comment]
@saraabdelsalam Updated the review comment please check again

**Comment by saraabdelsalam** [comment]
@YoussefWaelMohamedLotfy i have removed deperacted packages and made sure that all packages are updated, but there's one package (Microsoft.AspNetCore.Mvc.Abstraction) that is in use in the ocde and uninstalling it causes errors

**Comment by YoussefWaelMohamedLotfy** [comment]
> @YoussefWaelMohamedLotfy i have removed deperacted packages and made sure that all packages are updated, but there's one package (Microsoft.AspNetCore.Mvc.Abstraction) that is in use in the ocde and uninstalling it causes errors

After reviewing and knowing the problem for this, It turns out that this PR is now completed and ready for merging. Well Done @saraabdelsalam

**Review by YoussefWaelMohamedLotfy — APPROVED** [review]

**Pull request merged**
